### ISSUE TITLE
Add a LoadingStatusBar component

### ISSUE THREAD

**Issue by chrismayer** [meggsimum/cpsi-mapview#15]
A loading indicator as status bar, which can be placed in the footer, is needed.

![image](https://user-images.githubusercontent.com/1185547/44945316-e3290600-ade6-11e8-9c85-97b64c01bf6a.png)

**Comment by marcjansen** [comment]
see #7

**Comment by marcjansen** [comment]
WIP state of the BasiGX component is https://github.com/terrestris/BasiGX/pull/349
