### ISSUE TITLE
[LayerTree] Add toggle behavior for BaseLayer

### ISSUE THREAD

**Issue by chrismayer** [meggsimum/cpsi-mapview#16]
The LayerTree UI should be enhanced so only one "base layer" is visible at a time.

Since OL does not have a BaseLayer concept anymore (for good reasons) we need add some business logic to the tree, which provides this behavior.

**Comment by geographika** [comment]
From a conceptual viewpoint it makes sense that only one base layer should be visible as they would completely cover any underlying layer. 
With transparency options having 2 base layers visible could be a feature so they could be compared. 
The emptyLayer in the LayerFactory may no longer be relevant?
https://github.com/compassinformatics/mapview/blob/39616abc8b5e2f5a73e36ee4048665ffc835d09e/src/gis/LayerFactory.js#L35
