### ISSUE TITLE
Add Map Zoom in and Out Tools

### ISSUE THREAD

**Issue by geographika** [meggsimum/cpsi-mapview#18]
![image](https://user-images.githubusercontent.com/490840/45494933-73b1ff80-b772-11e8-93f1-55bd4a3207f6.png)

Zoom In Tool 
Zoom Out Tool

These were originally based in OL2 on OpenLayers.Control.ZoomBox()

See https://github.com/compassinformatics/mapview/blob/master/src/gis/NavigationTools.js

OL4 has https://openlayers.org/en/latest/examples/extent-interaction.html but couldn’t find an exact equivalent to OL2.

**Comment by marcjansen** [comment]
These are available in BasiGX

**Comment by marcjansen** [comment]
We have these now. If in the future we need e.g. zoo by rectangle we can either reopen or create a new issue.
