### ISSUE TITLE
Add Back and Next Buttons

### ISSUE THREAD

**Issue by geographika** [meggsimum/cpsi-mapview#20]
![image](https://user-images.githubusercontent.com/490840/45495093-d60b0000-b772-11e8-93d4-9e7e6b1aced7.png)

Originals based on OpenLayers.Control.NavigationHistory()
See https://github.com/compassinformatics/mapview/blob/master/src/gis/NavigationTools.js

**Comment by marcjansen** [comment]
Also a candidate for BasiGX

**Comment by geographika** [comment]
As in #23 x,y, and zoom level would be recorded in a stack and allow the user to move between previous and forward locations. 
The use of browser buttons would require the rest of the application state to be saved so not a priority at this stage.
