### ISSUE TITLE
Add Measure Tools

### ISSUE THREAD

**Issue by geographika** [meggsimum/cpsi-mapview#21]
![image](https://user-images.githubusercontent.com/490840/45495329-5c274680-b773-11e8-98fb-12501981e077.png)

Reuse http://terrestris.github.io/BasiGX/master/docs/#!/api/BasiGX.view.button.Measure ?

Originals used OpenLayers.Control.Measure and both line and polygons were supported. 

https://github.com/compassinformatics/mapview/blob/master/src/gis/MeasureAreaToolAction.js
https://github.com/compassinformatics/mapview/blob/master/src/gis/MeasureAreaTool.js

https://github.com/compassinformatics/mapview/blob/master/src/gis/MeasureLineTool.js
https://github.com/compassinformatics/mapview/blob/master/src/gis/MeasureLineToolAction.js

**Comment by marcjansen** [comment]
Yes, the mentioned button can be used

**Comment by marcjansen** [comment]
Fixed in #37
