### ISSUE TITLE
Add Timeslider

### ISSUE THREAD

**Issue by geographika** [meggsimum/cpsi-mapview#24]
See example at https://w08-mapserver.compass.ie/mapview-examples/examples/timeslider.html

Logic: https://github.com/compassinformatics/mapview/blob/master/src/gis/TimeSlider.js

Component : https://github.com/compassinformatics/mapview/blob/master/src/gis/TimeSliderComponent.js

Possible relevant: http://terrestris.github.io/BasiGX/master/docs/#!/api/BasiGX.util.WFS-static-method-getTimeFilterParts

In mapview layers could be configured to be "time-dependent" using the JSON config file.
A timeitem property could be one of "date" - when a full date would be used for filtering, or year, when just the year component of the date would be used for the filter. 
```
            "timeitem": "date", 
```

**Comment by marcjansen** [comment]
We have several applications dealing with the temporal dimension, a totally generic approach has yet to be developed.

**Comment by ahennr** [comment]
Range slider introduced in #49

**Comment by marcjansen** [comment]
Let's close this then! We can always reopen.
