### ISSUE TITLE
Add Coordinates to Map

### ISSUE THREAD

**Issue by geographika** [meggsimum/cpsi-mapview#25]
Add to toolbar at bottom of the map in EPSG:2157

![image](https://user-images.githubusercontent.com/490840/45495873-7281d200-b774-11e8-8a3c-24a16fb58551.png)

Can’t find an example at: https://openlayers.org/en/latest/examples/

See https://github.com/compassinformatics/mapview/blob/master/src/gis/CustomMap.js
**addMouseMoveCoord**

Latest mapview version has a full component similar to below:

![image](https://user-images.githubusercontent.com/490840/45495903-84fc0b80-b774-11e8-8d60-020d58a24af1.png)

See https://github.com/compassinformatics/mapview/blob/master/src/gis/Coordinates.js

**Comment by chrismayer** [comment]
This OL control should do the trick: http://openlayers.org/en/v4.6.5/apidoc/ol.control.MousePosition.html
Here as live example: https://openlayers.org/en/v4.6.5/examples/mouse-position.html

**Comment by geographika** [comment]
That looks perfect. 
I'm guessing to get the Irish projection EPSG:2157 that http://proj4js.org/ is needed. 
What is the best way of adding this dependency? Simply copying into the lib folder?

**Comment by marcjansen** [comment]
For proj4 we might be able to use npm... otherwise a git repo as submodule. copying a built js file is the last resort... and not a bad choice by itself.

**Comment by marcjansen** [comment]
Fixed in #39
