### ISSUE TITLE
Add Legend Panel

### ISSUE THREAD

**Issue by geographika** [meggsimum/cpsi-mapview#26]
LegendPanel component was available in GeoExt2: 
https://geoext.github.io/geoext2/examples/legendpanel/legendpanel.html

It has a whole set of associated classes in GeoExt2:

-	GeoExt.container.LayerLegend
-	GeoExt.container.UrlLegend
-	GeoExt.container.VectorLegend
-	GeoExt.container.WmsLegend

No example in GeoExt3: https://geoext.github.io/geoext3/

If large amounts of work then images can simply be hardcoded for now.

**Comment by chrismayer** [comment]
Maybe this could be a nice enhancement for GeoExt3. We should definitely discuss this.

**Comment by geographika** [comment]
WmsLegend and UrlLegend classes would be the priority - vector legends appear to be much more complex.
