### ISSUE TITLE
Open an ExtJS Form by clicking on a Vector Feature

### ISSUE THREAD

**Issue by geographika** [meggsimum/cpsi-mapview#28]
A single click should open a new instance of the form. 
The form will be contained in a separate project.

**Comment by chrismayer** [comment]
>A single click should open a new instance of the form.
The form will be contained in a separate project.

@geographika: The code, how to achieve this, is documented in #30. Please close this issue when you are happy with that.

**Comment by geographika** [comment]
After a few false starts and confusion about which controller was the default scope for an event, I have wired this up in an extended PL Map class. 

The extended Map can be seen at: https://github.com/compassinformatics/publiclighting/blob/master/app/view/main/Map.js

This wires up the event so it can be handled by an extended Map Controller class:

```
listeners: {
    'cmv-mapclick': 'onMapClick'
}
```
https://github.com/compassinformatics/publiclighting/blob/master/app/controller/MapController.js

I think this fits in with the MVVM Sencha architecture - a review of this approach would be appreciated.

**Comment by chrismayer** [comment]
The event-binding looks good to me. That's the way it should be done.

A good start to read about ViewController binding is https://docs.sencha.com/extjs/6.2.0/guides/application_architecture/view_controllers.html
