### ISSUE TITLE
Define date format in layer configuration 

### ISSUE THREAD

**Issue by ahennr** [meggsimum/cpsi-mapview#50]
Since date / time format can differ for certain layers, it should be configurable for each layer, for example by a further property `timeFormat` in layer factory

**Comment by marcjansen** [comment]
Yes. Please prepare it like this.

**Comment by marcjansen** [comment]
Introduced with #52 

`dateFormat` &rArr; allowed values are listed here: https://docs.sencha.com/extjs/6.2.0/classic/Ext.Date.html
