### ISSUE TITLE
Apply Styling to Vector Layers

### ISSUE THREAD

**Issue by geographika** [meggsimum/cpsi-mapview#57]
In the original mapview a WFS layer config could include a "sld" parameter which loaded an SLD file from a "sldUrl" property. This allowed styling to be applied from an SLD file. SLDs could be created dynamically, but it was faster to generate them on deployment and load these cached files). 

See https://github.com/compassinformatics/mapview/blob/master/src/gis/SldMixin.js and createWFS in LayerFactory.js

Does the https://github.com/terrestris/BasiGX/blob/master/src/util/SLD.js class allow an SLD file to be applied to a ol4 vector layer? If so then applying this in the Layer Factory may be a possible option. 

A more complex "slds" option built a radio button interface to allow switching between styling on the same vector layer to avoid reloading. This is likely to be a future requirement.

**Comment by chrismayer** [comment]
Vector styling is an open issue at all.

We noticed that you used SLD in the past. Unfortunately there is no more a built-in SLD-parser in OL (>=v3). There are several options:

One would be to integrate parts of the [GeoStyler](https://github.com/terrestris/geostyler/) library, which is currently developed by us (or better said mostly by terrestris at the moment). It has an SLD- and an OL-Parser. 
Another option could be using JSONIX for (De)Serializing the SLD. In my understanding this is the approach  https://github.com/terrestris/BasiGX/blob/master/src/util/SLD.js does. But this produces just plain JS-objects, which still have to be transformed to OL Styles.

There are surely more options, I just named the 2 which seem to fit best at first sight.

**Comment by geographika** [comment]
@chrismayer - thanks for the suggestions. Just to note I'm opening an issue as a reminder for future development, and not as an expectation for it to be fully developed!

All styling is currently in MapServer, so ideally this would be reused in someway. I have a Python library https://github.com/geographika/mappyfile that can parse this and export to different formats (or MapServer can export to SLD directly).

**Comment by chrismayer** [comment]
> Just to note I'm opening an issue as a reminder for future development

Perfect thanks!

> I have a Python library https://github.com/geographika/mappyfile

Cool :+1:  I'll have a look at this and I am sure we find good solution for bringing all this together.

**Comment by geographika** [comment]
Possible option? https://github.com/boundlessgeo/ol-mapbox-style
Export from MapServer to MapBox vector styling, then use the above library to apply the style. 

See also https://github.com/geographika/mappyfile/issues/66

**Comment by marcjansen** [comment]
With geostyler (only roughly tested):

```js
const sldParser = new GeoStylerSLDParser.SldStyleParser();
const olParser = new GeoStylerOpenlayersParser.OlStyleParser();

window.foo = (sld) => {
    sldParser.readStyle(sld)
        .then(gs => olParser.writeStyle(gs))
        .then(olStyle => {
            console.log(olStyle);
        });
};
```

**Comment by geographika** [comment]
Following discussions with @chrismayer the following approach will be attempted:

- Add GeoStylerSLDParser as a dependency to cpsi-mapview
- read the SLD location from the default.json file
- apply the styling (using a variant of the code snippet above from @marcjansen) to the layer when it is loaded in the Layer factory

I have uploaded a couple of SLD files for testing to: https://github.com/compassinformatics/publiclighting/tree/master/resources/data/styling

These can be applied to the "Accidents" WFS in https://github.com/compassinformatics/publiclighting/blob/master/resources/data/layers/default.json
