### ISSUE TITLE
Add Gazetteer

### ISSUE THREAD

**Issue by geographika** [meggsimum/cpsi-mapview#70]
It looks like there are UI controls in BasiGX e.g. ``BasiGX.view.form.field.GazetteerCombo``
Integrate these into the UI. Specify the choice of compatible back-ends. 

Uses Nominatim (OSM but proprietary) as backend. 
BasiGX.view.form.field.MultiSearchCombo may also be an option. Uses WFS. 

Decide upon API for any custom search.

**Comment by chrismayer** [comment]
As discussed in our call(s) I implemented a [generic GeoCoder component](https://github.com/geoext/geoext3/blob/master/src/form/field/GeocoderComboBox.js) for GeoExt, which can be used with Nominatim (default) and with your custom backends. The custom components for the services used in your old application are coming as a follow-up based on the GeoExt component.
