### ISSUE TITLE
Zoom in and Zoom Out by Box

### ISSUE THREAD

**Issue by geographika** [meggsimum/cpsi-mapview#72]
As noted in #18
Current mapview tools were based on OpenLayers.Control.ZoomBox
See notes in https://gis.stackexchange.com/questions/251952/zoombox-in-openlayers-3-4/252924 for new OL equivalent. 

Zooming in by box part of OL - add as a button.
Drop the zooming out box.

**Comment by annarieger** [comment]
Implemented in https://github.com/terrestris/BasiGX/pull/425

**Comment by annarieger** [comment]
Client part is addressed in #80.

**Comment by geographika** [comment]
@annarieger - I've added the zoom tools to a new project, with the latest BasiGX and cpsi-mapview projects as follows:

```
                {
                    xtype: 'basigx-button-zoomin',
                    toggleGroup: 'zoom'
                }, {
                    xtype: 'basigx-button-zoomout',
                    toggleGroup: 'zoom',
                    enableZoomOutWithBox: true
                },
```
The zoom boxes work great. There seems to be an issue with the ZoomIn button and single-clicks - it zooms the map out. See screencast below:

https://drive.google.com/file/d/1K4zzX23ziWis2-pPbRkymyUIyoS3n17w/view

**Comment by annarieger** [comment]
Issue confirmed and fixed in https://github.com/terrestris/BasiGX/pull/437.

Will be available in the demo app after merge and BasiGX submodule update

**Comment by geographika** [comment]
Thanks @annarieger all working now.
