### ISSUE TITLE
Port Zone Tool

### ISSUE THREAD

**Issue by geographika** [meggsimum/cpsi-mapview#73]
Port the OL2 based tool at https://github.com/compassinformatics/mapview/blob/master/src/gis/ZoneTool.js to the latest OL/ExtJS libraries. 
The tool depends on the following classes:

- https://github.com/compassinformatics/mapview/blob/master/src/gis/Solver.js
- https://github.com/compassinformatics/mapview/blob/master/src/gis/ServiceToolMixin.js

This tool relies on a backend service. Test JSON responses will be specified and example test files added to this ticket. A demo of the tool in action can be provided.

**Comment by geographika** [comment]
@weskamm - is it possible to select an existing polygon, and edit / drag vertices, and once completed trigger the service call again?

A screencast of the original functionality is at: https://drive.google.com/file/d/1192_HJ00FivB6WjGgth9rHNrrTqfoIiQ/view

**Comment by weskamm** [comment]
Yes this is already implemented. Try to modify an exisiting polygon by hovering over an vertex or line and you should be able to modify it.

**Comment by geographika** [comment]
@weskamm - thanks - I'd been used to the ol2 approach of clicking first. This way is smoother.
