### ISSUE TITLE
Create a ExtJS to OGC Filters Class

### ISSUE THREAD

**Issue by geographika** [meggsimum/cpsi-mapview#79]
Convert [ExtJS filters](https://docs.sencha.com/extjs/6.2.0/classic/Ext.grid.filters.Filters.html) - to OGC filters. 
The main purpose would be to have a grid of features coming from a service and an associated WMS layer. The grid could be filtered with the standard ExtJS column and then the filter converted to an OGC filter and applied to the WMS layer. 

Relevant server links:

- https://mapserver.org/development/rfc/ms-rfc-118.html
- https://docs.geoserver.org/latest/en/user/services/wms/vendor.html#filter

Possibly a candidate for GeoExt?

**Comment by weskamm** [comment]
The PR for GeoExt which solves this issue can be found here:
https://github.com/geoext/geoext3/pull/493

**Comment by geographika** [comment]
@weskamm / @chrismayer - as mentioned at https://github.com/geoext/geoext3/pull/493#issuecomment-485697359 how would you best recommend adding a WFS vector layer class variable into the WFS loader function created in the cpsi-mapview factory at: 
https://github.com/meggsimum/cpsi-mapview/blob/master/app/factory/Layer.js#L230

**Comment by annarieger** [comment]
Support for additional filters defined as instances of `Ext.grid.filter.filters` coming from e.g. `Ext.grid.Panel` or some other component is added in #87.

The changeset of #87 also includes an [example](https://github.com/meggsimum/cpsi-mapview/blob/master/app/factory/Layer.js#L250) how the `additionalFilters` can be set on the certain verctor layer. The approach is very similar to already existing possibility to set `timeFilters` (compare [here](https://github.com/meggsimum/cpsi-mapview/blob/fdde5f62221316b67e2b82431a9ee5c4534d6d87/app/controller/panel/TimeSlider.js#L91)).

Inside of `loaderFn` of your WFS layer you always operate on its source. So if some custom property (like `additionalFilters` or `timeFilters` or something else) is set you can simply access it inside of `loaderFn` with call like `this.get('someProperty')` - see for example [here](https://github.com/meggsimum/cpsi-mapview/blob/master/app/factory/Layer.js#L242) or [here](https://github.com/meggsimum/cpsi-mapview/blob/master/app/factory/Layer.js#L268).
```

**Comment by geographika** [comment]
@annarieger and @weskamm - thanks for the updates and example. I have everything working now in a local project.
