### ISSUE TITLE
[LayerFactory] Check how to deal with Google layers

### ISSUE THREAD

**Issue by chrismayer** [meggsimum/cpsi-mapview#8]
Since OpenLayer >= v3 does not support Google Maps layers we have to use a 3rd party plugin to get these layers into the app or we do not support them either.

**Comment by geographika** [comment]
In the short term Google layers are not a requirement. However longer-term Google StreetView integration is needed.

**Comment by marcjansen** [comment]
We should probably create a dedicated issue with the StreetView topic and close this one. What do you thin @geographika?

**Comment by geographika** [comment]
@marcjansen - I've just been reading up on the ol3+ / Google integration. Is the recommended 3rd party plugin https://github.com/mapgears/ol3-google-maps ? I will discuss in the call with @chrismayer 
I'm still unclear whether using this, even when paying/with an API key is breaking TOS. 

I can create a new issue for StreetView (and have working ExtJS4 / OL2 code). The traffic layer also looks interesting http://mapgears.github.io/ol3-google-maps/examples/dist/examples/traffic.html

**Comment by marcjansen** [comment]
> I've just been reading up on the ol3+ / Google integration. Is the recommended 3rd party plugin https://github.com/mapgears/ol3-google-maps ?

Yes, this is probably the best, but as you mention, this is 3rd party. right now this is hard to estimate for me.
