### ISSUE TITLE
[LayerFactory] Check for support of ImageWMS and TileWMS

### ISSUE THREAD

**Issue by chrismayer** [meggsimum/cpsi-mapview#9]
At the moment the layer-config type `wms` will create a layer with a source `ol.source.TileWMS`. We should check if there is a need to add layers with a source of type `ol.source.ImageWMS`.

**Comment by geographika** [comment]
@chrismayer - yes ImageWMS (a single full WMS image returned as a request) is a requirement. In OL2 there was quite a performance boost using this layer type for some dynamically generated layers.

**Comment by marcjansen** [comment]
From our meeting:

ol 2: <img src="">
ol > 3: image => canvas

Aside: how many layers will be used typically? ~6-7, at max (rarely: 70)
